services:
  modded_minecraft: 
    image: itzg/minecraft-server
    container_name: modded_minecraft
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    volumes:
      - ./test_mc_server_cache:/data